module.exports={active: "ajs",
                template: "xml",
                cutType: "utf8",
                defaultPage: "index.ajs",
                contentTypes: {".html": "text/html;charset=utf-8",
                               ".htm": "text/html;charset=utf-8",
                               ".jpg": "image/*",
                               ".png": "image/*",
                               ".gif": "image/*",
                               ".txt": "text/plain;charset=utf-8",
                               ".ajs": "text/html;charset=utf-8"}};
